FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist/liga-deportiva-angular ./dist/liga-deportiva-angular
EXPOSE 8080
CMD ["sh", "-c", "serve -s dist/liga-deportiva-angular -l ${PORT:-8080}"]
